#!/bin/sh
##scommands to run

work_dir=$(pwd)
templates="${work_dir}/templates"
scripts_folder="${work_dir}/tmp_scripts/"


if [ ! -e ${scripts_folder} ]
then
	mkdir ${scripts_folder}
fi

##First round, diagonal. missing only the 0%jobs (1v) using 100%large system (5)
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.2009v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.2009v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.2009v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.3006v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.3006v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.3006v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.40025v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.40025v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.40025v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.50v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.50v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.50v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.610v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.1008v/g' -e 's/SCITER/0/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.610v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.1008v/g' -e 's/SCITER/0/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sleep 1
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.201v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.201v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.201v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.3008v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.3008v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.3008v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.4003v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.4003v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.4003v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.5001v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.5001v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.5001v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.65v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.10085v/g' -e 's/SCITER/0/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.65v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.10085v/g' -e 's/SCITER/0/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sleep 1
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.2008v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.2008v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.2008v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.30065v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.30065v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.30065v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.4003v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.4003v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.4003v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.5001v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.5001v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.5001v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.615v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.10075v/g' -e 's/SCITER/0/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.615v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.10075v/g' -e 's/SCITER/0/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sleep 1
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.1008v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.10085v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.10075v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sleep 1
####
# Rest of the benchmarks, per system 0
###
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.2009v/g' -e 's/SCITER/0/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.3006v/g' -e 's/SCITER/0/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.40025v/g' -e 's/SCITER/0/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.50v/g' -e 's/SCITER/0/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.610v/g' -e 's/SCITER/0/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.201v/g' -e 's/SCITER/0/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.3008v/g' -e 's/SCITER/0/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.4003v/g' -e 's/SCITER/0/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.5001v/g' -e 's/SCITER/0/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.65v/g' -e 's/SCITER/0/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.2008v/g' -e 's/SCITER/0/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.30065v/g' -e 's/SCITER/0/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.4003v/g' -e 's/SCITER/0/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.5001v/g' -e 's/SCITER/0/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.615v/g' -e 's/SCITER/0/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sleep 1
#####
## Rest of the benchmarks, per system and file
####
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.1008v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.1008v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.3006v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.3006v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.40025v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.40025v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.50v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.50v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.610v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.610v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sleep 1
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.1008v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.1008v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.2009v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.2009v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.40025v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.40025v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.50v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.50v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.610v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.610v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
#sleep 1
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.1008v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.1008v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.2009v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.2009v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.3006v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.3006v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.50v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.50v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.610v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.610v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sleep 1
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.1008v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.1008v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.2009v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.2009v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.3006v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.3006v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.40025v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.40025v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.610v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl1.0k.610v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sleep 1
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.1008v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.2009v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.3006v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.40025v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl1.0k.50v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
######
##File 2
#######
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.10085v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.10085v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.3008v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.3008v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.4003v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.4003v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.5001v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.5001v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.65v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.65v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sleep 1
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.10085v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.10085v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.201v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.201v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.4003v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.4003v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.5001v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.5001v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.65v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.65v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sleep 1
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.10085v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.10085v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.201v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.201v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.3008v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.3008v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.5001v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.5001v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.65v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.65v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sleep 1
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.10085v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.10085v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.201v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.201v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.3008v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.3008v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.4003v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.4003v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.65v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl2.0k.65v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sleep 1
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.10085v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.201v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.3008v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.4003v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl2.0k.5001v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
#######
##File 3
########
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.10075v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.10075v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.30065v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.30065v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.4003v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.4003v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.5001v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.5001v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.615v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.615v/g' -e 's/SCITER/1/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sleep 1
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.10075v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.10075v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.2008v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.2008v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.4003v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.4003v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.5001v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.5001v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.615v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.615v/g' -e 's/SCITER/2/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sleep 1
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.10075v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.10075v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.2008v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.2008v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.30065v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.30065v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.5001v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.5001v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.615v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.615v/g' -e 's/SCITER/3/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sleep 1
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.10075v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.10075v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.2008v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.2008v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.30065v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.30065v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.4003v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.4003v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.615v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/32768/g' -e 's/SCFOLDER/sb1q1/g' -e 's/SCTRACE/128n.anl3.0k.615v/g' -e 's/SCITER/4/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' -e 's/SCQUEUEOPT/end/g' ${templates}/submit_local_feature.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sleep 1
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.10075v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.2008v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.30065v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.4003v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
sed -e 's/SCNNODES/1024/g' -e 's/SCNSOCKETS/1/g' -e 's/SCNCORES/32/g' -e 's/SCNMEMORY/65536/g' -e 's/SCFOLDER/ewhb1q1/g' -e 's/SCTRACE/128n.anl3.0k.5001v/g' -e 's/SCITER/5/g' -e 's/bf_queue_limit=x/bf_queue_limit=100/g' ${templates}/submit_local.sh >> ${scripts_folder}/tmp_simulation_script_x.sh
